### ISSUE TITLE
No rate limit in reset password

### ISSUE THREAD

**Issue by HitmanAlharbi** [echoCTF/echoCTF.RED#432] opened 2021-05-23 16:01 UTC
Hey guys,

No rate limit in password-reset page
I can send a lot of password-resets 
This can make a high load on server
And make a sleep in mails sending 

![B68C6AEE-1630-464E-B9FF-38BAACBB1162](https://user-images.githubusercontent.com/36328177/119267890-2f50b000-bbf9-11eb-813b-cc52ac754427.jpeg)

**Comment by proditis** [comment] 2021-05-23 16:05
duplicate of https://github.com/echoCTF/echoCTF.RED/issues/142

**Closed by proditis** 2021-05-23 16:05 UTC
