### ISSUE TITLE
Frontend 404 Page Error After Manual Installation

### ISSUE THREAD

**Issue by mirfansulaiman** [echoCTF/echoCTF.RED#544] opened 2022-01-14 03:58 UTC
Hi Team,

I am facing issues after manual installation, I followed this step https://echoctfred.readthedocs.io/INSTALL-LINUX/ and got an error after the installation was completed when opened the frontend page, for every page I got an error 404. 

![image](https://user-images.githubusercontent.com/6317984/149448928-84c5417c-8c96-4963-b171-bdfd1fb60786.png)

Do you have any solution to fix that? or did I miss something? 

OS: Debian 10
php: 7.2
composer: 2.2.4

**Comment by proditis** [comment] 2022-01-14 08:25
Hi there,

Can you please try the following and report back?
1. Check that `select count(*) from url_route` returns non 0
2. Check that `select val from sysconfig where id='routes'` returns a value other than `null` or `false`
3. Import the init `mysql < /etc/mysql-init.sql` and see if you get any errors

**Comment by mirfansulaiman** [comment] 2022-01-14 09:46
Hi @proditis ,

Here is the output:
1. select count(*) from url_route
![image](https://user-images.githubusercontent.com/6317984/149494596-854082e1-a309-40ec-8df0-d3a50efd8c02.png)

2. select val from sysconfig where id='routes'
![image](https://user-images.githubusercontent.com/6317984/149494627-fa1a9016-f94e-4084-9b37-85d2eeba7a92.png)

3. mysql < /etc/mysql-init.sql 
![image](https://user-images.githubusercontent.com/6317984/149494661-149c8ceb-74d3-4b22-be70-a6810fedc2cb.png)

**Comment by proditis** [comment] 2022-01-14 10:23
Thank you for the provided info @mirfansulaiman,

I guess the previous commands did not fix the problem :smiling_face_with_tear: ?

If not please try the following:
1. log into the backend with the admin user you created and go to Settings=>Configure
2. Fill in the details you'd like for your installation, making sure **Event Active** is checked.
3. Once done check the frontend again and see if the problem is gone

**Comment by mirfansulaiman** [comment] 2022-01-16 14:42
Hi @proditis ,

I just recreated the frontend app and still not working :'( 
it seems the route URL is missing on the frontend.

**Comment by proditis** [comment] 2022-01-16 16:15
This is not helping unfortunately. 

Did you follow my previous instructions? Is the database still named `ctftiket`? have you edited the `mysql-init` as instructed?

**Comment by mirfansulaiman** [comment] 2022-01-18 05:29
Yes, I'm following your instruction even database name `ctftiket` or `echoCTF`.

**Comment by proditis** [comment] 2022-01-18 08:31
The url rules are kept on memcache. If your database is not properly configured then there will be no url rules loaded there, just as your case. 

1. What is your database called?
2. Can you show your `mysql-init.sql`?
3. Show output of the following commands
```sql
SELECT memc_get('sysconfig:routes');
CALL init_mysql();
SELECT memc_get('sysconfig:routes');
```

**Comment by proditis** [comment] 2022-01-22 20:22
Closing this due to lack of information. Feel free top open a new issue if you're still having issues.

**Closed by proditis** 2022-01-22 20:22 UTC
